stages:          # List of stages for jobs, and their order of execution
  - compile-execute
  - execute-binary
  - deploy

compile-execute-job:       # This job runs in the build stage, which runs first.
  stage: compile-execute
  script:
    - echo "Compiling and executing the code..."
    - python3 -O main.py program.kln
    - echo "Compile complete."

execute-bin-job:   # This job runs in the test stage.
  stage: execute-binary    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Executing binary compiled binary file."
    - python3 -O main.py program.kbin
    - echo "Finished Executing Program Binary"
